name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Verify whitespace formatting
      run: dotnet format whitespace --verify-no-changes

    - name: Verify style formatting
      run: dotnet format style --verify-no-changes

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test (Unit)
      run: dotnet test --no-build --configuration Release --filter "FullyQualifiedName~Unit" --logger "trx;LogFileName=unit-tests.trx" --results-directory ./TestResults

    - name: Test (Functional)
      run: dotnet test --blame --no-build --configuration Release --filter "FullyQualifiedName~Functional" --logger "trx;LogFileName=functional-tests.trx" --results-directory ./TestResults

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./TestResults/*.trx

